/*
 * Copyright 2015-2016 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, 
 * either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
package org.lastaflute.job;

import java.util.List;

import org.dbflute.optional.OptionalThing;
import org.lastaflute.job.key.LaJobKey;
import org.lastaflute.job.key.LaJobUnique;
import org.lastaflute.job.subsidiary.CronConsumer;

/**
 * @author jflute
 * @since 0.2.0 (2016/01/11 Monday)
 */
public interface JobManager {

    /**
     * @param jobKey The job key auto-generated by scheduler. (NotNull)
     * @return The optional scheduled job, which is unique by job key. (NotNull, EmptyAllowed: when not found)
     */
    OptionalThing<LaScheduledJob> findJobByKey(LaJobKey jobKey);

    /**
     * @param jobUnique The value of job unique specified by application. (NotNull)
     * @return The optional scheduled job, which is unique by job key. (NotNull, EmptyAllowed: when not found)
     */
    OptionalThing<LaScheduledJob> findJobByUniqueOf(LaJobUnique jobUnique);

    List<LaScheduledJob> getJobList();

    void registerJob(CronConsumer oneArgLambda);

    void clearClosedJob();

    void destroySchedule();
}
